akka {
  actor {
    default-dispatcher {
      shutdown-timeout = 10s
    }
  }
  coordinated-shutdown {
    log-info-verbose = on
    default-phase-timeout = 10s

  }
  stdout-loglevel = "DEBUG"
  loglevel = "DEBUG"
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
}